name: Echollama Verbose Integration Test

on: [push, pull_request]

jobs:
  live-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build echollama
        run: go build -o echollama .

      - name: Start echollama server (background)
        run: |
          ./echollama serve &  # Start server in background
          sleep 8

      - name: Load stories15M.gguf test model
        run: |
          echo "FROM $(pwd)/models/stories15M.gguf" > models/stories15M.modelfile
          echo "PARAMETER temperature 0.7" >> models/stories15M.modelfile
          echo "PARAMETER num_ctx 2048" >> models/stories15M.modelfile
          echo "SYSTEM You are a test assistant that provides simple, direct responses for testing purposes." >> models/stories15M.modelfile
          ./echollama create stories15M -f models/stories15M.modelfile
          sleep 2

      - name: Send timestamped JSON requests (verbose)
        run: |
          TS1=$(date --iso-8601=ns)
          TS2=$(date --iso-8601=ns)
          # Verbose curl for first timestamp
          curl -v -X POST http://localhost:11434/api/generate \
            -H 'Content-Type: application/json' \
            -d '{
                  "model": "stories15M",
                  "prompt": "TIMESTAMP1: '$TS1'",
                  "stream": false
                }' | tee response1.json
          # Verbose curl for second timestamp
          curl -v -X POST http://localhost:11434/api/generate \
            -H 'Content-Type: application/json' \
            -d '{
                  "model": "stories15M",
                  "prompt": "TIMESTAMP2: '$TS2'",
                  "stream": false
                }' | tee response2.json

      - name: Show full JSON responses
        run: |
          cat response*.json

      - name: Show token info for both responses
        run: |
          jq .eval_count response1.json
          jq .eval_count response2.json

      - name: End-of-workflow verification (fail if responses missing tokens)
        run: |
          test "$(jq '.eval_count' response1.json)" -gt 0
          test "$(jq '.eval_count' response2.json)" -gt 0
